version: '2.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: topicos_avanzados
      MYSQL_ROOT_PASSWORD: 12345
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3306:3306"
    container_name: db
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
