version: '3.5'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: topicos_avanzados
      MYSQL_ROOT_PASSWORD: 12345
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3306:3306"
    container_name: db
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend