package los.trainees.backend.enums;

public enum ECategory {
    AGRO_FORESTAL_OTROS,
    COMERCIO_RETAIL_SERVICIOS,
    COMUNICACIONES_PUBLICIDAD,
    CONSTRUCCION_AFINES,
    ENTRETENIMIENTO_DEPORTE_CULTURA,
    INDUSTRIA_DISTRIBUCION,
    SERVICIO_CONSULTORIA_EDUCACION_AFINES,
    SERVICIO_SALUD_AFINES,
    SERVICIO_CORREO,
    SERVICIO_FINANCIERO_AFINES,
    SERVICIO_GASTRONOMICO_AFINES,
    SERVICIO_HOTELERIA_TURISMO,
    SERVICIO_PUBLICO_TRANSPORTE,
    SERVICIO_SEGURO_AFINES,
    SERVICIO_VIGILANCIA_LIMPIEZA,
    TELECOMUNICACIONES_DATOS
}
