spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/topicos_avanzados"
    username: "root"
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: "jwt_secret"
  expirationInMinutes: 1500
mail:
  username: ""
  password: ""