spring:
  datasource:
    url: ${AZURE_MYSQL_URL}
    username: ${AZURE_MYSQL_USERNAME}
    password: ${AZURE_MYSQL_PASSWORD}
jwt:
  secret: ${AZURE_JWT_SECRET}
  expirationInMinutes: 180
invite:
  emailUrl: ${AZURE_FRONTEND_URL}
mail:
  username: ${AZURE_MAIL_USERNAME}
  password: ${AZURE_MAIL_PASSWORD}