spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/topicos_avanzados"
    username: "root"
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: "jwt_secret"
  expirationInMinutes: 1500
invite:
  emailUrl: "http://localhost:3000/"
mail:
  username: "sisdistribuidos.no.reply@gmail.com"
  password: "tgaryhzzmziehmbp"