# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - frontend-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c06977ed6edf4de0ae653fa099cdf7f4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e959a98d27614a98afdcb501c44e4af7 }}

#    - name: Build and push container image to registry
#      run: |
#        cd app
#        docker build -t index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c06977ed6edf4de0ae653fa099cdf7f4 }}/lautarodarosa/proyecto-topicos-avanzados-frontend:${{ github.sha }} .
#        docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c06977ed6edf4de0ae653fa099cdf7f4 }}/lautarodarosa/proyecto-topicos-avanzados-frontend:${{ github.sha }}
#      env:
#        DOCKER_BUILDKIT: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontend-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_89f911f9306a4e5ba9c0a878c5ffc256 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c06977ed6edf4de0ae653fa099cdf7f4 }}/lautarodarosa/proyecto-topicos-avanzados-frontend:${{ github.sha }}'